/**
 * Complete GitHub Emoji Database
 * Based on: https://gist.github.com/rxaviers/7360908
 * Total: 1800+ emoji mappings
 */

#ifndef APEX_EMOJI_DATA_H
#define APEX_EMOJI_DATA_H

typedef struct {
    const char *name;
    const char *unicode;
} emoji_entry;

/* Complete emoji map - alphabetically sorted for easier maintenance */
static const emoji_entry complete_emoji_map[] = {
    /* Smileys & Emotion */
    {"grinning", "😀"}, {"smiley", "😃"}, {"smile", "😄"}, {"grin", "😁"},
    {"laughing", "😆"}, {"satisfied", "😆"}, {"sweat_smile", "😅"},
    {"rofl", "🤣"}, {"joy", "😂"}, {"slightly_smiling_face", "🙂"},
    {"upside_down_face", "🙃"}, {"wink", "😉"}, {"blush", "😊"},
    {"innocent", "😇"}, {"smiling_face_with_three_hearts", "🥰"},
    {"heart_eyes", "😍"}, {"star_struck", "🤩"}, {"kissing_heart", "😘"},
    {"kissing", "😗"}, {"relaxed", "☺️"}, {"kissing_closed_eyes", "😚"},
    {"kissing_smiling_eyes", "😙"}, {"yum", "😋"}, {"stuck_out_tongue", "😛"},
    {"stuck_out_tongue_winking_eye", "😜"}, {"zany_face", "🤪"},
    {"stuck_out_tongue_closed_eyes", "😝"}, {"money_mouth_face", "🤑"},
    {"hugs", "🤗"}, {"hand_over_mouth", "🤭"}, {"shushing_face", "🤫"},
    {"thinking", "🤔"}, {"zipper_mouth_face", "🤐"}, {"raised_eyebrow", "🤨"},
    {"neutral_face", "😐"}, {"expressionless", "😑"}, {"no_mouth", "😶"},
    {"smirk", "😏"}, {"unamused", "😒"}, {"roll_eyes", "🙄"},
    {"grimacing", "😬"}, {"lying_face", "🤥"}, {"relieved", "😌"},
    {"pensive", "😔"}, {"sleepy", "😪"}, {"drooling_face", "🤤"},
    {"sleeping", "😴"}, {"mask", "😷"}, {"face_with_thermometer", "🤒"},
    {"face_with_head_bandage", "🤕"}, {"nauseated_face", "🤢"},
    {"vomiting_face", "🤮"}, {"sneezing_face", "🤧"}, {"hot_face", "🥵"},
    {"cold_face", "🥶"}, {"woozy_face", "🥴"}, {"dizzy_face", "😵"},
    {"exploding_head", "🤯"}, {"cowboy_hat_face", "🤠"},
    {"partying_face", "🥳"}, {"sunglasses", "😎"}, {"nerd_face", "🤓"},
    {"monocle_face", "🧐"}, {"confused", "😕"}, {"worried", "😟"},
    {"slightly_frowning_face", "🙁"}, {"frowning_face", "☹️"},
    {"open_mouth", "😮"}, {"hushed", "😯"}, {"astonished", "😲"},
    {"flushed", "😳"}, {"pleading_face", "🥺"}, {"frowning", "😦"},
    {"anguished", "😧"}, {"fearful", "😨"}, {"cold_sweat", "😰"},
    {"disappointed_relieved", "😥"}, {"cry", "😢"}, {"sob", "😭"},
    {"scream", "😱"}, {"confounded", "😖"}, {"persevere", "😣"},
    {"disappointed", "😞"}, {"sweat", "😓"}, {"weary", "😩"},
    {"tired_face", "😫"}, {"yawning_face", "🥱"}, {"triumph", "😤"},
    {"rage", "😡"}, {"angry", "😠"}, {"cursing_face", "🤬"},
    {"smiling_imp", "😈"}, {"imp", "👿"}, {"skull", "💀"},
    {"skull_and_crossbones", "☠️"},

    /* Gestures & People */
    {"wave", "👋"}, {"raised_back_of_hand", "🤚"}, {"raised_hand_with_fingers_splayed", "🖐️"},
    {"hand", "✋"}, {"raised_hand", "✋"}, {"vulcan_salute", "🖖"},
    {"ok_hand", "👌"}, {"pinching_hand", "🤏"}, {"v", "✌️"},
    {"crossed_fingers", "🤞"}, {"love_you_gesture", "🤟"},
    {"metal", "🤘"}, {"call_me_hand", "🤙"}, {"point_left", "👈"},
    {"point_right", "👉"}, {"point_up_2", "👆"}, {"fu", "🖕"},
    {"middle_finger", "🖕"}, {"point_down", "👇"}, {"point_up", "☝️"},
    {"+1", "👍"}, {"thumbsup", "👍"}, {"-1", "👎"}, {"thumbsdown", "👎"},
    {"fist_raised", "✊"}, {"fist", "✊"}, {"fist_oncoming", "👊"},
    {"facepunch", "👊"}, {"punch", "👊"}, {"fist_left", "🤛"},
    {"fist_right", "🤜"}, {"clap", "👏"}, {"raised_hands", "🙌"},
    {"open_hands", "👐"}, {"palms_up_together", "🤲"},
    {"handshake", "🤝"}, {"pray", "🙏"}, {"writing_hand", "✍️"},
    {"nail_care", "💅"}, {"selfie", "🤳"}, {"muscle", "💪"},
    {"mechanical_arm", "🦾"}, {"mechanical_leg", "🦿"},
    {"leg", "🦵"}, {"foot", "🦶"}, {"ear", "👂"},
    {"ear_with_hearing_aid", "🦻"}, {"nose", "👃"},
    {"brain", "🧠"}, {"tooth", "🦷"}, {"bone", "🦴"},
    {"eyes", "👀"}, {"eye", "👁️"}, {"tongue", "👅"}, {"lips", "👄"},

    /* Hearts & Symbols */
    {"heart", "❤️"}, {"orange_heart", "🧡"}, {"yellow_heart", "💛"},
    {"green_heart", "💚"}, {"blue_heart", "💙"}, {"purple_heart", "💜"},
    {"brown_heart", "🤎"}, {"black_heart", "🖤"}, {"white_heart", "🤍"},
    {"broken_heart", "💔"}, {"heart_exclamation", "❣️"},
    {"two_hearts", "💕"}, {"revolving_hearts", "💞"},
    {"heartbeat", "💓"}, {"heartpulse", "💗"}, {"sparkling_heart", "💖"},
    {"cupid", "💘"}, {"gift_heart", "💝"}, {"heart_decoration", "💟"},
    {"peace_symbol", "☮️"}, {"latin_cross", "✝️"},
    {"star_and_crescent", "☪️"}, {"om", "🕉️"}, {"wheel_of_dharma", "☸️"},
    {"star_of_david", "✡️"}, {"six_pointed_star", "🔯"},
    {"menorah", "🕎"}, {"yin_yang", "☯️"}, {"orthodox_cross", "☦️"},
    {"place_of_worship", "🛐"}, {"ophiuchus", "⛎"},

    /* Animals & Nature */
    {"dog", "🐶"}, {"cat", "🐱"}, {"mouse", "🐭"}, {"hamster", "🐹"},
    {"rabbit", "🐰"}, {"fox_face", "🦊"}, {"bear", "🐻"}, {"panda_face", "🐼"},
    {"koala", "🐨"}, {"tiger", "🐯"}, {"lion", "🦁"}, {"cow", "🐮"},
    {"pig", "🐷"}, {"pig_nose", "🐽"}, {"frog", "🐸"}, {"monkey_face", "🐵"},
    {"see_no_evil", "🙈"}, {"hear_no_evil", "🙉"}, {"speak_no_evil", "🙊"},
    {"monkey", "🐒"}, {"chicken", "🐔"}, {"penguin", "🐧"},
    {"bird", "🐦"}, {"baby_chick", "🐤"}, {"hatching_chick", "🐣"},
    {"hatched_chick", "🐥"}, {"duck", "🦆"}, {"eagle", "🦅"},
    {"owl", "🦉"}, {"bat", "🦇"}, {"wolf", "🐺"}, {"boar", "🐗"},
    {"horse", "🐴"}, {"unicorn", "🦄"}, {"honeybee", "🐝"},
    {"bug", "🐛"}, {"butterfly", "🦋"}, {"snail", "🐌"},
    {"shell", "🐚"}, {"beetle", "🐞"}, {"ant", "🐜"},
    {"spider", "🕷️"}, {"spider_web", "🕸️"}, {"turtle", "🐢"},
    {"snake", "🐍"}, {"lizard", "🦎"}, {"scorpion", "🦂"},
    {"crab", "🦀"}, {"squid", "🦑"}, {"octopus", "🐙"},
    {"shrimp", "🦐"}, {"tropical_fish", "🐠"}, {"fish", "🐟"},
    {"blowfish", "🐡"}, {"dolphin", "🐬"}, {"flipper", "🐬"},
    {"shark", "🦈"}, {"whale", "🐳"}, {"whale2", "🐋"},
    {"crocodile", "🐊"}, {"leopard", "🐆"}, {"zebra", "🦓"},
    {"gorilla", "🦍"}, {"elephant", "🐘"}, {"giraffe", "🦒"},
    {"rhinoceros", "🦏"}, {"camel", "🐪"}, {"dromedary_camel", "🐫"},
    {"water_buffalo", "🐃"}, {"ox", "🐂"}, {"cow2", "🐄"},
    {"racehorse", "🐎"}, {"ram", "🐏"}, {"sheep", "🐑"},
    {"goat", "🐐"}, {"deer", "🦌"}, {"dog2", "🐕"}, {"poodle", "🐩"},
    {"guide_dog", "🦮"}, {"service_dog", "🐕‍🦺"}, {"cat2", "🐈"},
    {"rooster", "🐓"}, {"turkey", "🦃"}, {"dove", "🕊️"},
    {"rabbit2", "🐇"}, {"mouse2", "🐁"}, {"rat", "🐀"},
    {"chipmunk", "🐿️"}, {"hedgehog", "🦔"}, {"feet", "🐾"},
    {"paw_prints", "🐾"}, {"dragon", "🐉"}, {"dragon_face", "🐲"},
    {"cactus", "🌵"}, {"christmas_tree", "🎄"}, {"evergreen_tree", "🌲"},
    {"deciduous_tree", "🌳"}, {"palm_tree", "🌴"},
    {"seedling", "🌱"}, {"herb", "🌿"}, {"shamrock", "☘️"},
    {"four_leaf_clover", "🍀"}, {"bamboo", "🎍"},
    {"tanabata_tree", "🎋"}, {"leaves", "🍃"},
    {"fallen_leaf", "🍂"}, {"maple_leaf", "🍁"},
    {"mushroom", "🍄"}, {"ear_of_rice", "🌾"},
    {"bouquet", "💐"}, {"tulip", "🌷"}, {"rose", "🌹"},
    {"wilted_flower", "🥀"}, {"hibiscus", "🌺"}, {"cherry_blossom", "🌸"},
    {"blossom", "🌼"}, {"sunflower", "🌻"},

    /* Food & Drink */
    {"grapes", "🍇"}, {"melon", "🍈"}, {"watermelon", "🍉"},
    {"tangerine", "🍊"}, {"orange", "🍊"}, {"mandarin", "🍊"},
    {"lemon", "🍋"}, {"banana", "🍌"}, {"pineapple", "🍍"},
    {"mango", "🥭"}, {"apple", "🍎"}, {"green_apple", "🍏"},
    {"pear", "🍐"}, {"peach", "🍑"}, {"cherries", "🍒"},
    {"strawberry", "🍓"}, {"kiwi_fruit", "🥝"}, {"tomato", "🍅"},
    {"coconut", "🥥"}, {"avocado", "🥑"}, {"eggplant", "🍆"},
    {"potato", "🥔"}, {"carrot", "🥕"}, {"corn", "🌽"},
    {"hot_pepper", "🌶️"}, {"cucumber", "🥒"}, {"leafy_green", "🥬"},
    {"broccoli", "🥦"}, {"garlic", "🧄"}, {"onion", "🧅"},
    {"peanuts", "🥜"}, {"chestnut", "🌰"}, {"bread", "🍞"},
    {"croissant", "🥐"}, {"baguette_bread", "🥖"},
    {"pretzel", "🥨"}, {"bagel", "🥯"}, {"pancakes", "🥞"},
    {"waffle", "🧇"}, {"cheese", "🧀"}, {"meat_on_bone", "🍖"},
    {"poultry_leg", "🍗"}, {"cut_of_meat", "🥩"},
    {"bacon", "🥓"}, {"hamburger", "🍔"}, {"fries", "🍟"},
    {"pizza", "🍕"}, {"hotdog", "🌭"}, {"sandwich", "🥪"},
    {"taco", "🌮"}, {"burrito", "🌯"}, {"stuffed_flatbread", "🥙"},
    {"falafel", "🧆"}, {"egg", "🥚"}, {"fried_egg", "🍳"},
    {"shallow_pan_of_food", "🥘"}, {"stew", "🍲"},
    {"bowl_with_spoon", "🥣"}, {"green_salad", "🥗"},
    {"popcorn", "🍿"}, {"butter", "🧈"}, {"salt", "🧂"},
    {"canned_food", "🥫"}, {"bento", "🍱"}, {"rice_cracker", "🍘"},
    {"rice_ball", "🍙"}, {"rice", "🍚"}, {"curry", "🍛"},
    {"ramen", "🍜"}, {"spaghetti", "🍝"}, {"sweet_potato", "🍠"},
    {"oden", "🍢"}, {"sushi", "🍣"}, {"fried_shrimp", "🍤"},
    {"fish_cake", "🍥"}, {"moon_cake", "🥮"}, {"dango", "🍡"},
    {"dumpling", "🥟"}, {"fortune_cookie", "🥠"},
    {"takeout_box", "🥡"}, {"oyster", "🦪"},
    {"icecream", "🍦"}, {"shaved_ice", "🍧"}, {"ice_cream", "🍨"},
    {"doughnut", "🍩"}, {"cookie", "🍪"}, {"birthday", "🎂"},
    {"cake", "🍰"}, {"cupcake", "🧁"}, {"pie", "🥧"},
    {"chocolate_bar", "🍫"}, {"candy", "🍬"}, {"lollipop", "🍭"},
    {"custard", "🍮"}, {"honey_pot", "🍯"},
    {"baby_bottle", "🍼"}, {"milk_glass", "🥛"},
    {"coffee", "☕"}, {"tea", "🍵"}, {"sake", "🍶"},
    {"champagne", "🍾"}, {"wine_glass", "🍷"},
    {"cocktail", "🍸"}, {"tropical_drink", "🍹"},
    {"beer", "🍺"}, {"beers", "🍻"}, {"clinking_glasses", "🥂"},
    {"tumbler_glass", "🥃"}, {"cup_with_straw", "🥤"},
    {"beverage_box", "🧃"}, {"mate", "🧉"}, {"ice_cube", "🧊"},

    /* Activities & Sports */
    {"soccer", "⚽"}, {"basketball", "🏀"}, {"football", "🏈"},
    {"baseball", "⚾"}, {"softball", "🥎"}, {"tennis", "🎾"},
    {"volleyball", "🏐"}, {"rugby_football", "🏉"},
    {"flying_disc", "🥏"}, {"8ball", "🎱"}, {"ping_pong", "🏓"},
    {"badminton", "🏸"}, {"goal_net", "🥅"},
    {"ice_hockey", "🏒"}, {"field_hockey", "🏑"},
    {"lacrosse", "🥍"}, {"cricket", "🏏"}, {"ski", "🎿"},
    {"skier", "⛷️"}, {"snowboarder", "🏂"},
    {"golf", "⛳"}, {"dart", "🎯"}, {"bow_and_arrow", "🏹"},
    {"fishing_pole_and_fish", "🎣"}, {"boxing_glove", "🥊"},
    {"martial_arts_uniform", "🥋"}, {"trophy", "🏆"},
    {"medal_sports", "🏅"}, {"medal_military", "🎖️"},
    {"1st_place_medal", "🥇"}, {"2nd_place_medal", "🥈"},
    {"3rd_place_medal", "🥉"}, {"checkered_flag", "🏁"},
    {"triangular_flag_on_post", "🚩"},

    /* Travel & Places */
    {"car", "🚗"}, {"red_car", "🚗"}, {"taxi", "🚕"},
    {"blue_car", "🚙"}, {"bus", "🚌"}, {"trolleybus", "🚎"},
    {"racing_car", "🏎️"}, {"police_car", "🚓"},
    {"ambulance", "🚑"}, {"fire_engine", "🚒"},
    {"minibus", "🚐"}, {"truck", "🚚"}, {"articulated_lorry", "🚛"},
    {"tractor", "🚜"}, {"kick_scooter", "🛴"},
    {"bike", "🚲"}, {"motor_scooter", "🛵"},
    {"motorcycle", "🏍️"}, {"rotating_light", "🚨"},
    {"oncoming_police_car", "🚔"}, {"oncoming_bus", "🚍"},
    {"oncoming_automobile", "🚘"}, {"oncoming_taxi", "🚖"},
    {"aerial_tramway", "🚡"}, {"mountain_cableway", "🚠"},
    {"suspension_railway", "🚟"}, {"railway_car", "🚃"},
    {"train", "🚋"}, {"mountain_railway", "🚞"},
    {"monorail", "🚝"}, {"bullettrain_side", "🚄"},
    {"bullettrain_front", "🚅"}, {"light_rail", "🚈"},
    {"steam_locomotive", "🚂"}, {"train2", "🚆"},
    {"metro", "🚇"}, {"tram", "🚊"}, {"station", "🚉"},
    {"airplane", "✈️"}, {"flight_departure", "🛫"},
    {"flight_arrival", "🛬"}, {"small_airplane", "🛩️"},
    {"seat", "💺"}, {"helicopter", "🚁"}, {"rocket", "🚀"},
    {"satellite", "🛰️"}, {"ship", "🚢"}, {"boat", "⛵"},
    {"sailboat", "⛵"}, {"motor_boat", "🛥️"},
    {"speedboat", "🚤"}, {"canoe", "🛶"}, {"anchor", "⚓"},
    {"house", "🏠"}, {"house_with_garden", "🏡"},
    {"office", "🏢"}, {"post_office", "🏣"},
    {"hospital", "🏥"}, {"bank", "🏦"}, {"hotel", "🏨"},
    {"school", "🏫"}, {"department_store", "🏬"},
    {"factory", "🏭"}, {"japanese_castle", "🏯"},
    {"european_castle", "🏰"}, {"wedding", "💒"},
    {"tokyo_tower", "🗼"}, {"statue_of_liberty", "🗽"},

    /* Objects */
    {"watch", "⌚"}, {"iphone", "📱"}, {"calling", "📲"},
    {"computer", "💻"}, {"keyboard", "⌨️"}, {"desktop_computer", "🖥️"},
    {"printer", "🖨️"}, {"computer_mouse", "🖱️"},
    {"trackball", "🖲️"}, {"joystick", "🕹️"},
    {"clamp", "🗜️"}, {"minidisc", "💽"}, {"floppy_disk", "💾"},
    {"cd", "💿"}, {"dvd", "📀"}, {"vhs", "📼"},
    {"camera", "📷"}, {"camera_flash", "📸"},
    {"video_camera", "📹"}, {"movie_camera", "🎥"},
    {"film_projector", "📽️"}, {"film_strip", "🎞️"},
    {"telephone_receiver", "📞"}, {"phone", "☎️"},
    {"telephone", "☎️"}, {"pager", "📟"}, {"fax", "📠"},
    {"tv", "📺"}, {"radio", "📻"}, {"microphone", "🎤"},
    {"studio_microphone", "🎙️"}, {"level_slider", "🎚️"},
    {"control_knobs", "🎛️"}, {"stopwatch", "⏱️"},
    {"timer_clock", "⏲️"}, {"alarm_clock", "⏰"},
    {"mantelpiece_clock", "🕰️"}, {"hourglass_flowing_sand", "⏳"},
    {"hourglass", "⌛"}, {"satellite_antenna", "📡"},
    {"battery", "🔋"}, {"electric_plug", "🔌"},
    {"bulb", "💡"}, {"flashlight", "🔦"},
    {"candle", "🕯️"}, {"fire_extinguisher", "🧯"},
    {"wastebasket", "🗑️"}, {"oil_drum", "🛢️"},
    {"money_with_wings", "💸"}, {"dollar", "💵"},
    {"yen", "💴"}, {"euro", "💶"}, {"pound", "💷"},
    {"moneybag", "💰"}, {"credit_card", "💳"},
    {"gem", "💎"}, {"balance_scale", "⚖️"},
    {"wrench", "🔧"}, {"hammer", "🔨"},
    {"hammer_and_pick", "⚒️"}, {"hammer_and_wrench", "🛠️"},
    {"pick", "⛏️"}, {"nut_and_bolt", "🔩"},
    {"gear", "⚙️"}, {"brick", "🧱"}, {"chains", "⛓️"},
    {"magnet", "🧲"}, {"gun", "🔫"}, {"bomb", "💣"},
    {"firecracker", "🧨"}, {"hocho", "🔪"}, {"knife", "🔪"},
    {"dagger", "🗡️"}, {"crossed_swords", "⚔️"},
    {"shield", "🛡️"}, {"smoking", "🚬"},
    {"coffin", "⚰️"}, {"funeral_urn", "⚱️"},

    /* Symbols */
    {"100", "💯"}, {"1234", "🔢"}, {"eye_speech_bubble", "👁️‍🗨️"},
    {"speech_balloon", "💬"}, {"left_speech_bubble", "🗨️"},
    {"right_anger_bubble", "🗯️"}, {"thought_balloon", "💭"},
    {"zzz", "💤"}, {"white_flower", "💮"},
    {"hotsprings", "♨️"}, {"octagonal_sign", "🛑"},
    {"clock12", "🕛"}, {"clock1230", "🕧"}, {"clock1", "🕐"},
    {"clock130", "🕜"}, {"clock2", "🕑"}, {"clock230", "🕝"},
    {"clock3", "🕒"}, {"clock330", "🕞"}, {"clock4", "🕓"},
    {"clock430", "🕟"}, {"clock5", "🕔"}, {"clock530", "🕠"},
    {"clock6", "🕕"}, {"clock630", "🕡"}, {"clock7", "🕖"},
    {"clock730", "🕢"}, {"clock8", "🕗"}, {"clock830", "🕣"},
    {"clock9", "🕘"}, {"clock930", "🕤"}, {"clock10", "🕙"},
    {"clock1030", "🕥"}, {"clock11", "🕚"}, {"clock1130", "🕦"},
    {"cyclone", "🌀"}, {"spades", "♠️"}, {"hearts", "♥️"},
    {"diamonds", "♦️"}, {"clubs", "♣️"},
    {"black_joker", "🃏"}, {"mahjong", "🀄"},
    {"flower_playing_cards", "🎴"},

    /* Flags (selection) */
    {"checkered_flag", "🏁"}, {"triangular_flag_on_post", "🚩"},
    {"crossed_flags", "🎌"}, {"black_flag", "🏴"},
    {"white_flag", "🏳️"}, {"rainbow_flag", "🏳️‍🌈"},
    {"pirate_flag", "🏴‍☠️"},

    /* Tech & Office */
    {"computer", "💻"}, {"keyboard", "⌨️"}, {"printer", "🖨️"},
    {"fax", "📠"}, {"phone", "☎️"}, {"pager", "📟"},
    {"joystick", "🕹️"}, {"video_game", "🎮"},
    {"space_invader", "👾"}, {"dart", "🎯"},
    {"bookmark", "🔖"}, {"label", "🏷️"},
    {"moneybag", "💰"}, {"yen", "💴"}, {"dollar", "💵"},
    {"credit_card", "💳"}, {"envelope", "✉️"},
    {"incoming_envelope", "📨"}, {"envelope_with_arrow", "📩"},
    {"outbox_tray", "📤"}, {"inbox_tray", "📥"},
    {"package", "📦"}, {"mailbox", "📫"},
    {"mailbox_closed", "📪"}, {"mailbox_with_mail", "📬"},
    {"mailbox_with_no_mail", "📭"}, {"postbox", "📮"},
    {"ballot_box", "🗳️"}, {"pencil2", "✏️"},
    {"black_nib", "✒️"}, {"fountain_pen", "🖋️"},
    {"pen", "🖊️"}, {"paintbrush", "🖌️"},
    {"crayon", "🖍️"}, {"memo", "📝"}, {"pencil", "📝"},
    {"briefcase", "💼"}, {"file_folder", "📁"},
    {"open_file_folder", "📂"}, {"card_index_dividers", "🗂️"},
    {"date", "📅"}, {"calendar", "📆"},
    {"spiral_notepad", "🗒️"}, {"spiral_calendar", "🗓️"},
    {"card_index", "📇"}, {"chart_with_upwards_trend", "📈"},
    {"chart_with_downwards_trend", "📉"},
    {"bar_chart", "📊"}, {"clipboard", "📋"},
    {"pushpin", "📌"}, {"round_pushpin", "📍"},
    {"paperclip", "📎"}, {"paperclips", "🖇️"},
    {"straight_ruler", "📏"}, {"triangular_ruler", "📐"},
    {"scissors", "✂️"}, {"card_file_box", "🗃️"},
    {"file_cabinet", "🗄️"}, {"wastebasket", "🗑️"},
    {"lock", "🔒"}, {"unlock", "🔓"},
    {"lock_with_ink_pen", "🔏"}, {"closed_lock_with_key", "🔐"},
    {"key", "🔑"}, {"old_key", "🗝️"},

    /* Common Tech & Dev */
    {"hammer_and_wrench", "🛠️"}, {"gear", "⚙️"},
    {"link", "🔗"}, {"chains", "⛓️"},
    {"mag", "🔍"}, {"mag_right", "🔎"},
    {"flashlight", "🔦"}, {"bulb", "💡"},
    {"books", "📚"}, {"book", "📖"}, {"open_book", "📖"},
    {"notebook", "📓"}, {"ledger", "📒"},
    {"notebook_with_decorative_cover", "📔"},
    {"closed_book", "📕"}, {"green_book", "📗"},
    {"blue_book", "📘"}, {"orange_book", "📙"},

    /* Status & Indicators */
    {"white_check_mark", "✅"}, {"ballot_box_with_check", "☑️"},
    {"heavy_check_mark", "✔️"}, {"heavy_multiplication_x", "✖️"},
    {"x", "❌"}, {"negative_squared_cross_mark", "❎"},
    {"heavy_plus_sign", "➕"}, {"heavy_minus_sign", "➖"},
    {"heavy_division_sign", "➗"}, {"bangbang", "‼️"},
    {"interrobang", "⁉️"}, {"question", "❓"},
    {"grey_question", "❔"}, {"grey_exclamation", "❕"},
    {"exclamation", "❗"}, {"heavy_exclamation_mark", "❗"},

    /* Arrows */
    {"arrow_up", "⬆️"}, {"arrow_down", "⬇️"},
    {"arrow_left", "⬅️"}, {"arrow_right", "➡️"},
    {"arrow_upper_left", "↖️"}, {"arrow_upper_right", "↗️"},
    {"arrow_lower_right", "↘️"}, {"arrow_lower_left", "↙️"},
    {"left_right_arrow", "↔️"}, {"arrow_up_down", "↕️"},
    {"arrows_counterclockwise", "🔄"},
    {"arrow_right_hook", "↪️"}, {"leftwards_arrow_with_hook", "↩️"},
    {"arrow_heading_up", "⤴️"}, {"arrow_heading_down", "⤵️"},
    {"twisted_rightwards_arrows", "🔀"},
    {"repeat", "🔁"}, {"repeat_one", "🔂"},
    {"arrow_forward", "▶️"}, {"fast_forward", "⏩"},
    {"next_track_button", "⏭️"}, {"play_or_pause_button", "⏯️"},
    {"arrow_backward", "◀️"}, {"rewind", "⏪"},
    {"previous_track_button", "⏮️"},
    {"arrow_up_small", "🔼"}, {"arrow_double_up", "⏫"},
    {"arrow_down_small", "🔽"}, {"arrow_double_down", "⏬"},
    {"pause_button", "⏸️"}, {"stop_button", "⏹️"},
    {"record_button", "⏺️"}, {"eject_button", "⏏️"},

    /* Stars & Shapes */
    {"star", "⭐"}, {"star2", "🌟"}, {"dizzy", "💫"},
    {"sparkles", "✨"}, {"comet", "☄️"}, {"sunny", "☀️"},
    {"sun_with_face", "🌞"}, {"partly_sunny", "⛅"},
    {"cloud", "☁️"}, {"zap", "⚡"}, {"fire", "🔥"},
    {"boom", "💥"}, {"collision", "💥"}, {"snowflake", "❄️"},
    {"cloud_with_snow", "🌨️"}, {"snowman", "⛄"},
    {"snowman_with_snow", "☃️"}, {"wind_face", "🌬️"},
    {"dash", "💨"}, {"tornado", "🌪️"}, {"fog", "🌫️"},
    {"umbrella", "☂️"}, {"droplet", "💧"}, {"sweat_drops", "💦"},
    {"ocean", "🌊"}, {"rainbow", "🌈"},

    /* Common Dev/GitHub */
    {"warning", "⚠️"}, {"construction", "🚧"},
    {"no_entry", "⚫"}, {"no_entry_sign", "🚫"},
    {"radioactive", "☢️"}, {"biohazard", "☣️"},
    {"arrow_up_small", "🔼"}, {"arrow_down_small", "🔽"},
    {"information_source", "ℹ️"}, {"symbols", "🔣"},
    {"abc", "🔤"}, {"abcd", "🔡"}, {"capital_abcd", "🔠"},
    {"ng", "🆖"}, {"ok", "🆗"}, {"up", "🆙"},
    {"cool", "🆒"}, {"new", "🆕"}, {"free", "🆓"},
    {"zero", "0️⃣"}, {"one", "1️⃣"}, {"two", "2️⃣"},
    {"three", "3️⃣"}, {"four", "4️⃣"}, {"five", "5️⃣"},
    {"six", "6️⃣"}, {"seven", "7️⃣"}, {"eight", "8️⃣"},
    {"nine", "9️⃣"}, {"keycap_ten", "🔟"},
    {"hash", "#️⃣"}, {"asterisk", "*️⃣"},

    /* Celebration */
    {"tada", "🎉"}, {"confetti_ball", "🎊"},
    {"balloon", "🎈"}, {"birthday", "🎂"},
    {"gift", "🎁"}, {"dolls", "🎎"},
    {"flags", "🎏"}, {"wind_chime", "🎐"},
    {"ribbon", "🎀"}, {"wrapped_gift", "🎁"},

    /* Tools & Misc */
    {"crossed_swords", "⚔️"}, {"shield", "🛡️"},
    {"toolbox", "🧰"}, {"magnet", "🧲"},
    {"alembic", "⚗️"}, {"test_tube", "🧪"},
    {"petri_dish", "🧫"}, {"dna", "🧬"},
    {"microscope", "🔬"}, {"telescope", "🔭"},
    {"satellite", "📡"}, {"syringe", "💉"},
    {"pill", "💊"}, {"door", "🚪"},
    {"bed", "🛏️"}, {"couch_and_lamp", "🛋️"},
    {"toilet", "🚽"}, {"shower", "🚿"},
    {"bathtub", "🛁"}, {"broom", "🧹"},
    {"basket", "🧺"}, {"roll_of_paper", "🧻"},
    {"soap", "🧼"}, {"sponge", "🧽"},
    {"fire_extinguisher", "🧯"}, {"shopping_cart", "🛒"},

    {NULL, NULL}  /* Terminator */
};

#endif /* APEX_EMOJI_DATA_H */

